### ISSUE TITLE
Toolmaking books Forge and Crucible absent from loot.

### ISSUE THREAD

**Issue by RubahFox** [mjrice/7DaysModlets#2]
Looks like after the hammer and forge removal update that the book for toolmaking today that unlocks the forge and crucible were not added to the loot xml and are thus not being found in game.

Below is what I added on my server running this mod to correct it inside the loot.xml file under the toolmaking today section.
``

	<item name="Toolmaking Today: Forge"        prob="1" />
	<item name="Toolmaking Today: Crucible"     prob="1" />
``

**Comment by mjrice** [comment]
should be fixed now thanks
